"""add money

Revision ID: a9c0cf7c101d
Revises: fc0176c3d26f
Create Date: 2026-08-20 15:27:44.418821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c0cf7c101d'
down_revision: Union[str, Sequence[str], None] = 'fc0176c3d26f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.add_column(
            sa.Column("money", sa.Integer(), nullable=True)
        )

    op.execute("UPDATE users SET money = 100 WHERE money IS NULL")

    with op.batch_alter_table("users") as batch_op:
        batch_op.alter_column(
            "money",
            existing_type=sa.Integer(),
            nullable=False
        )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'money')
    # ### end Alembic commands ###
